# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ASDKSampleApp' do
  
# pod 'CardIO'
# pod 'ASDKCore', :podspec =>  "https://raw.githubusercontent.com/TinkoffCreditSystems/tinkoff-asdk-ios/master/ASDKCore.podspec"
# pod 'ASDKUI', :podspec =>  "https://raw.githubusercontent.com/TinkoffCreditSystems/tinkoff-asdk-ios/master/ASDKUI.podspec"
  
  pod 'CardIO', '~> 5.4.1'
  pod 'ASDKCore', :podspec =>  "https://raw.githubusercontent.com/nikolay-petrov/tinkoff-asdk-ios/master/ASDKCore.podspec"
  pod 'ASDKUI', :podspec =>  "https://raw.githubusercontent.com/nikolay-petrov/tinkoff-asdk-ios/master/ASDKUI.podspec"
  
end

